### ISSUE TITLE
Gameplay restricted to bottom left corner

### ISSUE THREAD

**Issue by eisnerguy1** [Sappharad/Sonic-1-2-2013-Decompilation#1]
With Sonic 1 & Sonic 2, the game window shrinks down to the bottom left corner once you actually start or resume a game:
<img width="636" alt="Screen Shot 2022-03-29 at 6 52 57 PM" src="https://user-images.githubusercontent.com/3295271/160909456-464d983e-d121-4ad2-9e17-3a09ddd4cc94.png">
<img width="636" alt="Screen Shot 2022-03-29 at 6 45 23 PM" src="https://user-images.githubusercontent.com/3295271/160909466-6654f7be-54b3-41fa-95cf-1fc9d6263968.png">

<img width="636" alt="Screen Shot 2022-03-29 at 6 53 46 PM" src="https://user-images.githubusercontent.com/3295271/160909540-3e7ba0cd-6d6e-41bc-9366-1bfd7b1efbcb.png">
<img width="636" alt="Screen Shot 2022-03-29 at 6 54 04 PM" src="https://user-images.githubusercontent.com/3295271/160909547-464a31a1-65f2-4667-b65f-d821adfb8184.png">

**Comment by Cincoln** [comment]
me too :(

**Comment by Cincoln** [comment]
when i use dev mode, activate mods or use fullscreen the screen stuck and small as well.

**Comment by Cincoln** [comment]
I was able to get full-screen working properly on my m1 mac with mods. I set FullScreen to false, Borderless to true, WindowScale to 1, and ScreenWidth to 424. If this doesnt help I also have a link to the file https://drive.google.com/file/d/1py0--4oplgLgYl_kM6BZEOCxJ4Mxqr_j/view?usp=sharing.
